all: icsea clean
	@echo "----------------------------------------------------------------"
	@echo ""
	@echo "   slides for MDEbug@MODELS18"
	@echo ""
	@echo "----------------------------------------------------------------"

icsea: 
	pdflatex sirius*.tex
	pdflatex sirius*.tex
	pdflatex sirius*.tex

clean:
	rm sirius*.log 
	rm sirius*.nav 
	rm sirius*.toc
	rm sirius*.snm	
	rm sirius*.aux
	rm sirius*.out		