all: fr en mini short nano clean

fr: 
	pdflatex CVFerdjoukh.tex
	pdflatex CVFerdjoukh.tex

mini: 
	pdflatex CVFerdjoukh-mini.tex
	pdflatex CVFerdjoukh-mini.tex

en: 
	pdflatex CVFerdjoukh_en.tex
	pdflatex CVFerdjoukh_en.tex

short:
	pdflatex CVFerdjoukh_en-short.tex
	pdflatex CVFerdjoukh_en-short.tex

nano:
	pdflatex CVFerdjoukh-nano.tex
	pdflatex CVFerdjoukh-nano.tex

clean:
	rm *.aux
	rm *.out
	rm *.log	